# Generated by Django 2.0.7 on 2018-07-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickstart',
            name='is_active',
            field=models.CharField(default='true', max_length=50),
        ),
        migrations.AddField(
            model_name='quickstart',
            name='is_approved',
            field=models.CharField(default='false', max_length=50),
        ),
    ]
